name: ChestShop

main: com.Acrobot.ChestShop.ChestShop

database: true
version: 3.00


author: Acrobot
description: >
             A chest shop for economy mods.
commands:
  iteminfo:
    aliases: [ii,iinfo]
    description: Lists item id and names
    usage: |
           /<command> (item name/item ID/alias)
           () - optional
  csVersion:
    aliases: cv
    description: Shows the ChestShop's version
    usage: |
           /<command>
  chestOptions:
    aliases: [coptions,cop,cpref]
    description: Sets ChestShop's preferences - Not implemented yet
    usage: |
           /<command> (option) (value)
           () - optional