name: ChestShop

main: com.Acrobot.ChestShop.ChestShop

database: true
version: 3.00


author: Acrobot
description: >
             A chest shop for economy mods.
commands:
  buy:
    aliases: chBuy
    description: Toggles mode to buying
    usage: |
           /<command>
  sell:
    aliases: chSell
    description: Toggles mode to selling
    usage: |
           /<command>
  iteminfo:
    aliases:
    description: Lists item id and names
    usage: |
           /<command> <partial item name or id>
  csVersion:
    aliases:
    description: Shows the ChestShop's version
    usage: |
           /<command>